export const kebab = [
  { id: 1, name: "Doner Kebab", price: 12 },
  { id: 2, name: "Shish Kebab", price: 15 },
  { id: 3, name: "Adana Kebab", price: 10 },
  { id: 4, name: "Iskender Kebab", price: 18 },
  { id: 5, name: "Lahmacun", price: 8 },
  { id: 6, name: "Chicken Shawarma", price: 14 },
  { id: 7, name: "Falafel Kebab", price: 9 },
  { id: 8, name: "Gyro Kebab", price: 16 },
  { id: 9, name: "Vegetable Kebab", price: 11 },
  { id: 10, name: "Kofta Kebab", price: 13 },
  { id: 11, name: "Lamb Kebab", price: 17 },
  { id: 12, name: "Fish Kebab", price: 14 },
  { id: 13, name: "Paneer Tikka Kebab", price: 11 },
  { id: 14, name: "Mushroom Kebab", price: 9 },
  { id: 15, name: "Tandoori Chicken Kebab", price: 16 },
];

export const drinks = [
  { id: 16, name: "Cola", price: 5 },
  { id: 17, name: "Orange Juice", price: 4 },
  { id: 18, name: "Apple Juice", price: 6 },
  { id: 19, name: "Pineapple Juice", price: 5 },
  { id: 20, name: "Mango Smoothie", price: 7 },
  { id: 21, name: "Strawberry Milkshake", price: 6 },
  { id: 22, name: "Iced Coffee", price: 6 },
  { id: 23, name: "Lemon Iced Tea", price: 3 },
  { id: 24, name: "Watermelon Lemonade", price: 4 },
  { id: 25, name: "Ginger Beer", price: 4 },
  { id: 26, name: "Mojito", price: 7 },
  { id: 27, name: "Peach Iced Tea", price: 3 },
  { id: 28, name: "Mint Lime Soda", price: 5 },
  { id: 29, name: "Cranberry Spritzer", price: 5 },
  { id: 30, name: "Pomegranate Mocktail", price: 6 },
];
